version: '3'

services:
  app:
    build: .
    tty: true
    volumes:
      - ${APP_CODE_PATH_HOST}:/app
    ports:
      - "8080:4000"
    command: >
      ash -c '
      rm -rf _book
      gitbook init &&
      gitbook serve'
